spring:
  application:
    name: brownie-ai-agent
  profiles:
    active: local
  # springdoc-openapi??????
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.brownie.brownieaiagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
#指定某一个类的输出级别，比如现在的SimpleLoggerAdvisor可以输出>=debug级别的日志
logging:
  level:
    org.springframework.ai.chat.client.advisor.org.springframework.ai.chat.client.advisor.MyLoggerAdvisor: debug